export const SET_CALCULATOR_INFORMATION = "SET_CALCULATOR_INFORMATION";
export const GET_CALCULATOR_RESULT_FETCH = "GET_CALCULATOR_RESULT_FETCH";
export const GET_CALCULATOR_RESULT_SUCCESS = "GET_CALCULATOR_RESULT_SUCCESS";