export const OPEN_LOADER = 'OPEN_LOADER';
export const CLOSE_LOADER = 'CLOSE_LOADER';

export const LOAD_CITIES_FETCH = 'LOAD_CITIES_FETCH';
export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';
export const LOAD_PROFESSIONS_FETCH = 'LOAD_PROFESSIONS_FETCH';
export const LOAD_PROFESSIONS_SUCCESS = 'LOAD_PROFESSIONS_SUCCESS';
export const LOAD_DATAS_COMMONS = 'LOAD_DATAS_COMMONS';