export const GET_CONSTRUCTIONS = 'GET_CONSTRUCTIONS';
export const SELECT_CONSTRUCTION = 'SELECT_CONSTRUCTION';

// export const UPDATE_DATA_SELECTED_CONSTRUCTION = "UPDATE_DATA_SELECTED_CONSTRUCTION";
