export const PUBLISH_POST = "PUBLISH_POST";
export const PUBLISH_PROJECT = "PUBLISH_PROJECT";

export const EVENTS_POSTS_SUCCESS = "EVENTS_POSTS_SUCCESS";
export const OPPORTUNITIES_POSTS_SUCCESS = "OPPORTUNITIES_POSTS_SUCCESS";
export const NEWS_POSTS_SUCCESS = "NEWS_POSTS_SUCCESS";
export const PROJECTS_POSTS_SUCCESS = "PROJECTS_POSTS_SUCCESS";

export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";


export const FETCH_EVENTS_POSTS = "FETCH_EVENTS_POSTS";
export const FETCH_NEWS_POSTS = "FETCH_NEWS_POSTS";
export const FETCH_OPPORTUNITIES_POSTS = "FETCH_OPPORTUNITIES_POSTS";
export const FETCH_PROJECTS_POSTS = "FETCH_PROJECTS_POSTS";

