export const PRODUCT_ADDED_SUCCESS = "PRODUCT_ADDED_SUCCESS";
export const PRODUCT_ELIMINATED_SUCCESS = "PRODUCT_ELIMINATED_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const SHOPPINGCART_FETCH = "SHOPPINGCART_FETCH";
export const PRODUCT_ADD_FETCH = "PRODUCT_ADD_FETCH";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FETCH = "PRODUCT_LIST_FETCH";