export const dataFormatter : any = {
  ReinforcingSteel: "Acero de refuerzo\nØ 1/2",
  RodSix: "Varilla/barra\nX 6mt",
  SteelStirrups: "Acero de estribos\nØ 3/8",
  BlackTieWire: "Alambre negro\npara amarrar",
  Sand: "Arena",
  Boulder: "Piedras",
  Framework: "Formaleta",
  Cement: "Cemento",
  SantaFeBlocklon: "Bloquelon santa fe (7,7 x 22,8 x 80)",
  ElectroweldedMesh: "Malla\nelectrosoldada",
  EasyPlateProfile: "Perfil ipe para\nplaca facil",
  PolystirenePanel: "Caseton de icopor (0,4 * 100)",
  BracesAndFramework: "Formaleta y puntales",
  MetaldeckFoil: "Lamina metaldeck Cal.20 - 0.85",
  MeshTape: "Cinta malla",
  PlateScrew: "Tornillo de placa",
  PaperTape: "Cinta papel",
  ZProfile: "Perfil Z",
  JoistCaliber: "Vigueta Cal.26",
  TwoByTwoAngle: "Angulo 2 x 2",
  PaintTypeTwo: "Pintura tipo 2",
  DrywallSheet: "Placa drywall (1,22 x 2,44)",
  InteriorPaint: "PinturaInterior",
  ExteriorPaint: "PinturaExterior",
  Water: "Agua",
  SikaOne: "sika 1",
  SmoothStucco: "Estuco liso",
  PlasticStucco: "Estuco plastico",
  CeramicFloor: "Piso ceramico",
  PorcelainFloor: "Piso porcelanato",
  VeneerPorCer: "Enchape ceramico/porcelanato",
  CeramicTileAdhesive: "Pegante para piso ceramico",
  PorcelainTileAdhesive: "Pegante para piso porcelanato",
  FloorAdhesivePorCer: "Pegante para ceramico/porcelanato",
  Nozzle: "boquilla",
  Gauze: "Estopa",
  BagSeparators: "Bolsa separadores",
  Blocks: "Bloques",
};
